# Generated by Django 6.0.6 on 2026-06-17 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Caveau',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=20, unique=True)),
                ('section', models.CharField(max_length=50)),
                ('bloc', models.CharField(blank=True, max_length=50, null=True)),
                ('allee', models.CharField(blank=True, max_length=50, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('longueur', models.FloatField(default=2.5)),
                ('largeur', models.FloatField(default=1.0)),
                ('statut', models.CharField(choices=[('DISPONIBLE', 'Disponible'), ('RESERVE', 'Réservé'), ('OCCUPE', 'Occupé'), ('NON_EXPLOITABLE', 'Non exploitable')], default='DISPONIBLE', max_length=20)),
                ('nom_defunt', models.CharField(blank=True, max_length=100, null=True)),
                ('date_naissance', models.DateField(blank=True, null=True)),
                ('date_deces', models.DateField(blank=True, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('proprietaire_nom', models.CharField(blank=True, max_length=100, null=True)),
                ('proprietaire_telephone', models.CharField(blank=True, max_length=20, null=True)),
                ('proprietaire_email', models.EmailField(blank=True, max_length=254, null=True)),
            ],
            options={
                'ordering': ['section', 'numero'],
            },
        ),
    ]
