# Generated by Django 6.0.5 on 2026-06-21 23:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cimetiere', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_nom', models.CharField(max_length=100)),
                ('client_prenom', models.CharField(max_length=100)),
                ('client_email', models.EmailField(max_length=254)),
                ('client_telephone', models.CharField(max_length=20)),
                ('client_adresse', models.TextField(blank=True, null=True)),
                ('nom_defunt', models.CharField(max_length=100)),
                ('prenom_defunt', models.CharField(max_length=100)),
                ('date_naissance', models.DateField()),
                ('date_deces', models.DateField()),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('VALIDE', 'Validé'), ('REFUSE', 'Refusé'), ('ANNULE', 'Annulé')], default='EN_ATTENTE', max_length=20)),
                ('date_reservation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('commentaire', models.TextField(blank=True, null=True)),
                ('caveau', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='cimetiere.caveau')),
            ],
            options={
                'ordering': ['-date_reservation'],
            },
        ),
    ]
