# Generated by Django 6.0.5 on 2026-06-24 21:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cimetiere', '0002_reservation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('mot_de_passe', models.CharField(max_length=255)),
                ('role', models.CharField(choices=[('ADMIN', 'Administrateur'), ('AGENT', 'Agent de terrain'), ('SECRETAIRE', 'Secrétariat'), ('CLIENT', 'Client')], default='CLIENT', max_length=20)),
                ('telephone', models.CharField(blank=True, max_length=20, null=True)),
                ('date_inscription', models.DateTimeField(auto_now_add=True)),
                ('est_actif', models.BooleanField(default=True)),
                ('mfa_active', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Concession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proprietaire_nom', models.CharField(max_length=200)),
                ('proprietaire_telephone', models.CharField(max_length=20)),
                ('proprietaire_email', models.EmailField(max_length=254)),
                ('type_concession', models.CharField(choices=[('TEMPORAIRE', 'Temporaire'), ('PERPETUELLE', 'Perpétuelle')], max_length=20)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField(blank=True, null=True)),
                ('date_renouvellement', models.DateField(blank=True, null=True)),
                ('est_active', models.BooleanField(default=True)),
                ('document_scan', models.FileField(blank=True, null=True, upload_to='concessions/')),
                ('caveau', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cimetiere.caveau')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('type_paiement', models.CharField(choices=[('MOBILE_MONEY', 'Mobile Money'), ('AIRTEL_MONEY', 'Airtel Money'), ('ESPECE', 'Espèces'), ('VIREMENT', 'Virement')], max_length=20)),
                ('reference', models.CharField(max_length=100, unique=True)),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('VALIDE', 'Validé'), ('ANNULE', 'Annulé')], default='EN_ATTENTE', max_length=20)),
                ('date_transaction', models.DateTimeField(auto_now_add=True)),
                ('date_validation', models.DateTimeField(blank=True, null=True)),
                ('commentaire', models.TextField(blank=True, null=True)),
                ('concession', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cimetiere.concession')),
            ],
        ),
        migrations.CreateModel(
            name='Exhumation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('defunt_nom', models.CharField(max_length=200)),
                ('defunt_prenom', models.CharField(max_length=200)),
                ('date_deces', models.DateField()),
                ('date_demande', models.DateTimeField(auto_now_add=True)),
                ('date_exhumation', models.DateField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('DEMANDE', 'Demande'), ('EN_ATTENTE', 'En attente de validation'), ('APPROUVEE', 'Approuvée'), ('REFUSEE', 'Refusée'), ('REALISEE', 'Réalisée')], default='DEMANDE', max_length=20)),
                ('raison', models.TextField()),
                ('lieu_depot', models.CharField(blank=True, max_length=200, null=True)),
                ('autorisation', models.FileField(blank=True, null=True, upload_to='exhumations/')),
                ('concession', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cimetiere.concession')),
                ('valide_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cimetiere.utilisateur')),
            ],
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=255)),
                ('model_name', models.CharField(max_length=100)),
                ('object_id', models.IntegerField()),
                ('details', models.JSONField(default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('date_action', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cimetiere.utilisateur')),
            ],
        ),
    ]
