# Generated by Django 6.0.5 on 2026-06-25 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cimetiere', '0003_utilisateur_concession_transaction_exhumation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='mfa_code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='role',
            field=models.CharField(choices=[('SUPER_ADMIN', 'Super administrateur'), ('ADMIN', 'Administrateur'), ('AGENT', 'Agent de terrain'), ('SECRETAIRE', 'Secrétariat'), ('CLIENT', 'Client')], default='CLIENT', max_length=20),
        ),
    ]
