# Generated by Django 6.0.5 on 2026-06-25 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cimetiere', '0004_utilisateur_mfa_code_alter_utilisateur_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigurationCimetiere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('superficie_totale', models.FloatField(default=0.0)),
                ('zones', models.JSONField(default=list)),
                ('taille_tombeau_longueur', models.FloatField(default=2.5)),
                ('taille_tombeau_largeur', models.FloatField(default=1.0)),
                ('zones_non_exploitables', models.IntegerField(default=0)),
                ('chemins', models.FloatField(default=0.0)),
                ('date_modification', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='mfa_active',
            field=models.BooleanField(default=True),
        ),
    ]
