# Generated by Django 6.0.5 on 2026-06-26 16:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cimetiere', '0005_configurationcimetiere_alter_utilisateur_mfa_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='MFACode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=6)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_expiration', models.DateTimeField()),
                ('est_utilise', models.BooleanField(default=False)),
            ],
        ),
        migrations.DeleteModel(
            name='ConfigurationCimetiere',
        ),
        migrations.RemoveField(
            model_name='utilisateur',
            name='mfa_code',
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='mfa_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='role',
            field=models.CharField(choices=[('SUPER_ADMIN', 'Super Administrateur'), ('ADMIN', 'Administrateur'), ('AGENT', 'Agent de terrain'), ('SECRETAIRE', 'Secrétariat'), ('CLIENT', 'Client')], default='CLIENT', max_length=20),
        ),
        migrations.AddField(
            model_name='mfacode',
            name='utilisateur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cimetiere.utilisateur'),
        ),
    ]
