# Generated by Django 6.0.5 on 2026-06-26 17:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cimetiere', '0006_mfacode_delete_configurationcimetiere_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='concession',
            name='caveau',
        ),
        migrations.RemoveField(
            model_name='exhumation',
            name='concession',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='concession',
        ),
        migrations.RemoveField(
            model_name='exhumation',
            name='valide_par',
        ),
        migrations.AlterModelOptions(
            name='caveau',
            options={},
        ),
        migrations.AlterModelOptions(
            name='reservation',
            options={},
        ),
        migrations.RemoveField(
            model_name='caveau',
            name='allee',
        ),
        migrations.RemoveField(
            model_name='caveau',
            name='date_deces',
        ),
        migrations.RemoveField(
            model_name='caveau',
            name='date_modification',
        ),
        migrations.RemoveField(
            model_name='caveau',
            name='date_naissance',
        ),
        migrations.RemoveField(
            model_name='caveau',
            name='proprietaire_email',
        ),
        migrations.RemoveField(
            model_name='caveau',
            name='proprietaire_telephone',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='client_adresse',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='commentaire',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='date_modification',
        ),
        migrations.RemoveField(
            model_name='utilisateur',
            name='est_actif',
        ),
        migrations.AlterField(
            model_name='caveau',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='caveau',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cimetiere.caveau'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='statut',
            field=models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('VALIDE', 'Validé'), ('REFUSE', 'Refusé')], default='EN_ATTENTE', max_length=20),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='mfa_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Administrateur'), ('CLIENT', 'Client')], default='CLIENT', max_length=20),
        ),
        migrations.DeleteModel(
            name='AuditLog',
        ),
        migrations.DeleteModel(
            name='Concession',
        ),
        migrations.DeleteModel(
            name='Transaction',
        ),
        migrations.DeleteModel(
            name='Exhumation',
        ),
    ]
