# Generated by Django 6.0.6 on 2026-07-08 06:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cimetiere', '0008_concession_utilisateur_est_actif_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigurationTerrain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('superficie_totale', models.FloatField(default=50000)),
                ('zones', models.CharField(default='Zone A, Zone B, Zone C', max_length=255)),
                ('longueur_tombeau', models.FloatField(default=2.5)),
                ('largeur_tombeau', models.FloatField(default=1.0)),
                ('zones_non_exploitables', models.FloatField(default=0)),
                ('chemins_m2', models.FloatField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='exhumation',
            name='demandeur_nom',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='exhumation',
            name='demandeur_telephone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='numero_telephone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='concession',
            name='caveau',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='concessions', to='cimetiere.caveau'),
        ),
        migrations.AlterField(
            model_name='concession',
            name='proprietaire_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='concession',
            name='proprietaire_telephone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='concession',
            name='type_concession',
            field=models.CharField(choices=[('TEMPORAIRE', 'Temporaire'), ('PERPETUELLE', 'Perpétuelle')], default='TEMPORAIRE', max_length=20),
        ),
        migrations.AlterField(
            model_name='exhumation',
            name='date_deces',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='exhumation',
            name='defunt_prenom',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='exhumation',
            name='raison',
            field=models.TextField(blank=True, default=''),
        ),
    ]
